services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - .:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8859:80"
        restart: unless-stopped
        environment:
            TZ: "Europe/Moscow"
        depends_on:
            - app
            - db
            - node
            - redis

    app:
        build:
            context: .
            dockerfile: _docker/app/php.Dockerfile
            args:
                UID: 1000
                GID: 1000
        volumes:
            - .:/var/www
        restart: unless-stopped
        environment:
            - TZ=Europe/Moscow


    db:
        image: postgres
        restart: always
        volumes:
            - ../pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"

    node:
        build:
            context: .
            dockerfile: _docker/nodejs/node.Dockerfile
        working_dir: /var/www
        user: root
        volumes:
            - .:/var/www
            - node_modules:/var/www/node_modules
        ports:
            - "5173:5173"
        tty: true
        command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6382:6379"
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DATABASES=16

volumes:
    redis_data:
    node_modules:
